
spring:
  logging:
    level:
      root: INFO

#  datasource:
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    #url: jdbc:postgresql://users_db:5432/monitor_users
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
  exposed:
    show-sql: true
    generate-ddl: true
#  profiles:
#    active: prd
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    h2:
      console:
        enabled: true
        path: /h2-console
#server:
#  port: 3000
security:
  jwt:
    secret-key: U1hnYrA4I9jRGCFOuF-BiaJ8TytvJ25jK24hmd-R55fUO_qn
    expiration-time: 3600000